//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnet_wcf_app.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GodinaStudiranjaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OIBField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GodinaStudiranja {
            get {
                return this.GodinaStudiranjaField;
            }
            set {
                if ((this.GodinaStudiranjaField.Equals(value) != true)) {
                    this.GodinaStudiranjaField = value;
                    this.RaisePropertyChanged("GodinaStudiranja");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime {
            get {
                return this.ImeField;
            }
            set {
                if ((object.ReferenceEquals(this.ImeField, value) != true)) {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OIB {
            get {
                return this.OIBField;
            }
            set {
                if ((this.OIBField.Equals(value) != true)) {
                    this.OIBField = value;
                    this.RaisePropertyChanged("OIB");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IFaksServis")]
    public interface IFaksServis {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaksServis/NoviStudent", ReplyAction="http://tempuri.org/IFaksServis/NoviStudentResponse")]
        void NoviStudent(string ime, int oib, int god_stud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaksServis/NoviStudent", ReplyAction="http://tempuri.org/IFaksServis/NoviStudentResponse")]
        System.Threading.Tasks.Task NoviStudentAsync(string ime, int oib, int god_stud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaksServis/ListaStudenata", ReplyAction="http://tempuri.org/IFaksServis/ListaStudenataResponse")]
        dnet_wcf_app.ServiceReference1.Student[] ListaStudenata();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFaksServis/ListaStudenata", ReplyAction="http://tempuri.org/IFaksServis/ListaStudenataResponse")]
        System.Threading.Tasks.Task<dnet_wcf_app.ServiceReference1.Student[]> ListaStudenataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFaksServisChannel : dnet_wcf_app.ServiceReference1.IFaksServis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FaksServisClient : System.ServiceModel.ClientBase<dnet_wcf_app.ServiceReference1.IFaksServis>, dnet_wcf_app.ServiceReference1.IFaksServis {
        
        public FaksServisClient() {
        }
        
        public FaksServisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FaksServisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FaksServisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FaksServisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void NoviStudent(string ime, int oib, int god_stud) {
            base.Channel.NoviStudent(ime, oib, god_stud);
        }
        
        public System.Threading.Tasks.Task NoviStudentAsync(string ime, int oib, int god_stud) {
            return base.Channel.NoviStudentAsync(ime, oib, god_stud);
        }
        
        public dnet_wcf_app.ServiceReference1.Student[] ListaStudenata() {
            return base.Channel.ListaStudenata();
        }
        
        public System.Threading.Tasks.Task<dnet_wcf_app.ServiceReference1.Student[]> ListaStudenataAsync() {
            return base.Channel.ListaStudenataAsync();
        }
    }
}
